In [3]:
import numpy as np

In [4]:
a = np.array([1,2])
b = np.array([3,4])

In [5]:
print(a + b)

[4 6]


In [6]:
print(2 * a)

[2 4]


In [7]:
x = np.array([2, 4])
y = np.array([1, 3])

In [8]:
print(x + y)
print(x - y)
print(3 * x)

[3 7]
[1 1]
[ 6 12]


In [9]:
dot = np.dot(a, b)
print(dot)

11


In [10]:
u = np.array([2, 5])
v = np.array([4, 1])
dot = np.dot(u, v)
print(dot)

13


In [29]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])
C = A @ B
print(C)

[[ 4  4]
 [10  8]]


In [30]:
C = np.matmul(A, B) #same as @
print(C)

[[ 4  4]
 [10  8]]


In [18]:
D = np.array([[1, 0],
              [0, 1]])
E = np.array([[4, 1], [2, 2]])
print(np.matmul(D, E))

[[4 1]
 [2 2]]


In [31]:
A = np.array([[1, 2, 3], 
              [4, 5, 6]])
print(A.T) # Tranposition

[[1 4]
 [2 5]
 [3 6]]


In [25]:
v = np.array([3, 4])
print(np.linalg.norm(v)) #Pythagorean theorem
u = np.array([6, 8])
print(np.linalg.norm(u))

5.0
10.0


In [54]:
I = np.eye(2)  # Identity matrix
Z = np.array([[4, 7],
              [2, 6]])
inv_Z = np.linalg.inv(Z)
print(I)
print(inv_Z)
print(np.dot(Z, inv_Z))  # ~ Identity
print(np.allclose(np.dot(Z, inv_Z), np.eye(2))) #checks if matrices are approximately equal

[[1. 0.]
 [0. 1.]]
[[ 0.6 -0.7]
 [-0.2  0.4]]
[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]
True


### Why is the result not the Identity Matrix

- `-1.11022302e-16` and `1.11022302e-16` are approximately 0, and this occurs because computers represent numbers in binary, this can be confirmed by running `np.allclose`